### ISSUE TITLE
Testing - Integration Tests

### ISSUE THREAD

**Issue by krogk** [krogk/AgroPi#21]
**Description**
Set of Tests aimed for ensuring all parts of the software work correctly

**Comment by andrewsg3** [comment]
Think we have all the same hardware, will do some testing

**Comment by krogk** [comment]
Implemented Integration tests in #eec47dbbf993188d9b5812b924ca09eb98d9945d
Sampler & Controller functionality tested, more information about this coming in next few commits with documentation.
