### ISSUE TITLE
GPIO Driver & Relay Board Object

### ISSUE THREAD

**Issue by krogk** [krogk/AgroPi#27]
**Problem?**
Elego relay board is controlled by changing the state of the GPIO pins, currently there are no set of functions to do this,  

**Solution**
A GPIO driver object would be ideal, an instance of this object would be passed to the relay board object and the controller would controller hold both object and this object would be called in the sampler callback in actuator handler function.

**Alternatives**
Alternativley the GPIO code could be contained within the relay board object, however if we need additional functionality for the GPIO such as PWM we would need to restructured the code then.

*Testing context**
The testing should be focused on the relay board object, switching each relays on and off should be 

In Addition a set of requirements needs to be created and the implementation should aim to achieve these requirements.

**Comment by andrewsg3** [comment]
If we're pressed for time, wouldn't wiringpi do the trick?

**Comment by krogk** [comment]
Implemented in 78f01b468e57e9e33bd845090bab05f4cd63a354
