### ISSUE TITLE
Website - Graphs don't update

### ISSUE THREAD

**Issue by krogk** [krogk/AgroPi#30]
**Bug**
Website receives the data but it doesn't update graphs

**Comment by andrewsg3** [comment]
Kamil and I experienced this last night. Laptop had empty spaces for graphs, PI had graphs that weren't updating. Hoping to test and resolve this evening, as it is stable on Kamils system as of today.

**Comment by krogk** [comment]
Fixed in eb3189d40ee8903e9e15c79e68cbf8187e9acc7d
See commit for details
